# Generated by Django 2.1 on 2020-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagefiled',
            field=models.ImageField(default='default.png', upload_to='profile_dir'),
        ),
    ]
