# Generated by Django 2.1 on 2020-04-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0002_auto_20200411_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagefiled',
            field=models.ImageField(default='defaul1t.png', upload_to='profile_dir'),
        ),
    ]
